version: '3'
services:
  db:
    image: postgres:15-alpine
    container_name: gcce-db
    network_mode: "host"
    restart: unless-stopped
    environment:
      POSTGRES_DB: 'gcce'
      POSTGRES_USER: 'gcce'
      POSTGRES_PASSWORD: '1234'
    #ports:
      #- '5432:5432'
    expose:
      - '5432'
    volumes:
      - ./volumes/pg-data:/var/lib/postgresql/data
  hop:
    image: apache/hop:2.1.0
    environment:
      HOP_SERVER_USER: 'admin'
      HOP_SERVER_PASS: 'admin'
      HOP_SERVER_PORT: '80'
      HOP_SERVER_HOSTNAME: '0.0.0.0'
      HOP_LOG_LEVEL: 'basic'
      HOP_PROJECT_FOLDER: '/files'
      HOP_RUN_CONFIG: 'local'
    restart: unless-stopped
    ports:
      - '80:80'
    volumes:
      - ./volumes/hop:/files
 
